name: .NET Core

on: [push, pull_request]

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
   
    - name: Install dependencies 
      run: dotnet restore WebStore/WebStore.sln
        
    - name: Build
      run: dotnet build WebStore/WebStore.sln -c Release
      #run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test WebStore/WebStore.sln --no-restore
        
